FORMAT: 1A
HOST: http://47.100.35.106:8084/

# 学工API

学工后台API文档
# Data Structures


## StudentData(object)
+ Id: `DIRECTION_CD` (number, required) - 主键id
+ Name: `张三` (string,required) -姓名 
+ Sex:   `男`         (string)  -性别
+ Birth:       `1991-10-10`     (string) -生日 
+ Nationality:  `中国`    (string,required)      - 国籍
+ Nation:       `汉`    (string)         - 民族
+ StudentType:    `统招 `  (string)     - 留学生、统招
+ NativePlace:    `陕西`  (string)     - 籍贯
+ PlaceOfDomicile:  `  `   (string)  - 户籍所在地
+ IsFloat:        ` `   (string)         - 是否流动人口
+ Hukouxingzhi:   ` `   (string)     - 户口性质
+ IdentityType:   ` `   (string)     - 身份证类型
+ Idcard:         ` `   (string)          - 身份证号码
+ Idardtime:      ` `   (string)      - 身份证件有效期
+ PoliticsType:   ` `   (string)    - 政治面貌
+ HealthState:    ` `   (string)     - 身体状况
+ Marriage:       ` `   (string)      - 婚姻状况
+ Photo:          ` `   (string)            - 照片
+ IdentityPhoto1: ` `   (string) - 身份证正面图片
+ IdentityPhoto2:  ` `  (string) (string)  - 身份证反面图片
+ StartSchooleTime:  ` ` (string) - 入学时间
+ SchoolId:   ` `  (string)   - 学籍号
+ Grade:      ` `  (string)      - 年级
+ Academy:    ` `  (string)    - 院系
+ Major:      ` ` (string)      - 专业
+ Class:      ` `  (string)      - 班级
+ ClassId;    ` `  (string)    - 班内学号
+ KaoshengId; ` `  (string) - 考生号
+ Cellphone;  ` ` (string) -电话号码
+ Address;    ` ` (string)   - 家庭住址
+ Postcode;   ` ` (string)  - 邮政编码
+ Telephone;  ` ` (string) - 固定电话
+ Email;   ` ` (string) - 邮箱
+ FatherName;    ` `  (string) -父亲姓名
+ FatherWorkPlace;   ` `  (string)
+ Fatherphone;    ` ` (string)
+ MotherName;    ` `  (string) -母亲姓名
+ MontherWorkPlace;  ` `  (string)
+ Montherphone;  ` `  (string)
+ PinyinName;  ` ` (string)
+ EnglishName;   ` `   (string)
+ OldName;    ` `  (string)   - 曾用名
+ BloodType;   ` ` (string) - 血型
+ IsOnlyChild;    ` `  (string)   - 独生子女
+ Speciality;   ` ` (string) - 特长
+ IsHMT;   ` `  (string) - 港澳台侨胞
+ Religion;   ` `   (string) -  宗教
+ ShengyuanProvince:   ` ` (string) - 省份
+ Height:  ` ` (string)- 身高
+ Weight:  ` ` (string)- 体重

## Error400 (object)

+    code: ` ` (string) - 结果状态
+    message: ` ` (string) - 原因


## ZhuxuePostData(object)
+ Id:          `1`         (number,required) - 主键
+ WorkType:             ` ` (string)    - 工作类型 校内、企业实习、企业兼职
+ WorkFenlei:           ` ` (string)  - 工作分类
+ WorkPlace::            ` ` (string)   - 工作地点
+ WorkXingshi:          ` ` (string) - 工作形式
+ Worktime:             ` ` (string)
+ PaymentType:          ` ` (string)
+ Salary:               ` ` (string)
+ IsOffical:            ` ` (string)
+ Paytype:              ` ` (string)
+ PayChannel:           ` ` (string)
+ WorkDescribe:         ` ` (string)
+ PushCompany:          ` ` (string)
+ Responsible:          ` ` (string)          - 负责人
+ ResponsibleCellphone: ` ` (string) - 负责人联系方式
+ ResponsibleType:      ` ` (string)      - 负责人类型
+ WorkAccessory:        ` ` (string)        - 工作详情附件
+ Remark:               ` ` (string)
+ ValidityTime:         ` ` (string)
+ Number:               ` ` (string)
+ Status:               ` ` (string) - 岗位状态

## ZhuxueCompanyData(object)
+ Id:          `1`         (number,required) - 主键
+ CompanyName:      ` ` (string) -企业名称
+ CompanyType:      ` ` (string) -
+ CompanyWeb:       ` ` (string) -
+ CompanyContacts:  ` ` (string) -
+ ContactCellphone: ` ` (string) -
+ CompanyEmail:     ` ` (string) -
+ CompanyTelphone:  ` ` (string) -
+ CompanyFax:       ` ` (string) -
+ CompanyAddr:      ` ` (string) -
+ CompanyPostcode:  ` ` (string) -
+ BusinessLicense:  ` ` (string) -
+ BusinessPhoto:    ` ` (string) -
+ Other:            ` ` (string) -
+ Remark:           ` ` (string) -
+ AuditStatus:      ` ` (string) - //审核状态

# Group 学生
## 学生 [/students]
###获取所有学生 [GET /students]

+ Response 200 (application/json)
     + Attributes(array[StudentData])
  


###新增一个学生 [POST /students]


+ Request (application/json)
     + Attributes(StudentData)
+ Response 201 (application/json)
    + Attributes(Error400)

            
### 获取一个指定学生 [GET /students/{id}]

+ Response 200 (application/json)
    + Attributes(StudentData)
    
+ Response 400 (application/json)
    + Attributes(Error400)

### 删除一个指定学生 [DELETE /students/{id}]
+ Response 204 

### 修改一个指定学生 [PUT /students/{id}]
+ Response 200 (application/json)
    + Attributes(StudentData)
    
+ Response 400 (application/json)
    + Attributes(Error400)

    
# Group 岗位
## 岗位 [/zhuxueposts]


###获取所有岗位 [GET /students]

+ Response 200 (application/json)
     + Attributes(array[StudentData])
  


###新增一个岗位 [POST /zhuxueposts]


+ Request (application/json)

+ Response 201 (application/json)
    + Attributes(Error400)

            
### 获取一个指定岗位 [GET /zhuxueposts/{id}]

+ Response 200 (application/json)
    + Attributes(StudentData)
    
+ Response 400 (application/json)
    + Attributes(Error400)

### 删除一个指定岗位 [DELETE /zhuxueposts/{id}]
+ Response 204 

### 修改一个指定岗位 [PUT /zhuxueposts/{id}]
+ Response 200 (application/json)
    + Attributes(StudentData)
    
+ Response 400 (application/json)
    + Attributes(Error400)

    
# Group 企业
## 企业 [/zhuxuecompanys]

###获取所有企业 [GET /zhuxuecompanys]

+ Response 200 (application/json)
     + Attributes(array[StudentData])
  


###新增一个企业 [POST /zhuxuecompanys]


+ Request (application/json)
        
+ Response 201 (application/json)
    + Attributes(Error400)

            
### 获取一个指定企业 [GET /zhuxuecompanys/{id}]

+ Response 200 (application/json)
    + Attributes(StudentData)
    


### 删除一个指定企业 [DELETE /zhuxuecompanys/{id}]
+ Response 204 

### 修改一个指定岗位 [PUT /zhuxuecompanys/{id}]
+ Response 200 (application/json)
  + Attributes(Error400)
    
+ Response 400 (application/json)
    + Attributes(Error400)